### ISSUE TITLE
Lock Command Issue

### ISSUE THREAD

**Issue by flaviofornazier** [pahihu/mumps#1]
Hi Mr. Andras,

I hope, you, your family and friends are well.

Steps to reproduce the error:

- Set local variable g(0) to any valid global value. 
- Set local variable C to any valid value.
- Execute the below command in your terminal.
   L (@g(0),^ZX(C))

Thank you in advanced.

PS: Please let me know if you don't accept issues, I will understand you. =)

**Comment by pahihu** [comment]
Hi,

I hope, I've fixed it.
Please, test it with the new sources!

Regards,
Andras Pahi

**Comment by flaviofornazier** [comment]
Hi Mr. Andras,

Issue fixed. 

Congratulations! MV2 is very fast.

Thanks a lot! =)
