### ISSUE TITLE
Syntax Errors

### ISSUE THREAD

**Issue by flaviofornazier** [pahihu/mumps#2]
Hi Mr.Pahihu,

I hope you're doing well.

Steps to reproduce the errors:

- Extract the attached database that I created to make the process easier for you.
- Mount the attached database.
- Set your terminal type to vt220.
- Login to Mumps using ^%M routine, so you will see the error.
- Type D ^TKFORME and answer "Y" to create the form samples.
- To recreate the error, just kill ^TKDISP, ^TKDISPL , ^TKFORMS globals and execute TKFORME routine again.
- I'm using Ubuntu 20 Desktop, so the devices are configured as "pts/x" in ^TK global.

For information purposes only, this TK-FORM version works fine on the last Mr.Ray version, (i.e. v1.71 from 2018).
I'll only be able to verify if there more errors if you fix this. =)

Thank you in advance.

![tk-form_mv2_error](https://github.com/pahihu/mumps/assets/50641373/370beccd-31fb-42ba-8ad5-4cdd99e5e373)
[tkformdb_mv2.tar.gz](https://github.com/pahihu/mumps/files/12591482/tkformdb_mv2.tar.gz)

**Comment by pahihu** [comment]
Hi Mr. Fornazier,

It fails on MUMPS V2 on the stable branch,
works on MUMPS V1.71 and the master branch of my repo.

This expression produces the syntax error:

  S $P(sp,$S(B[".":".",1:" "),132)=""
   ^ Command syntax error - At line 7

I will fix it.

Regards,
Andras Pahi

**Comment by pahihu** [comment]
Fixed. I have introduced this bug in 2017. Don't ask why.

Regards,
Andras Pahi

**Comment by flaviofornazier** [comment]
Mr.Pahihu,

Issue fixed. TK-Form is working like a charm on V2. Thank you very much.

I would like to start a free of charge project for home and small business in Brazil, 
so I ask you: Which branch should I use for production?

Regards.

PS: A minimal implementation of Post Method in %WWW would be great! :)

**Comment by pahihu** [comment]
Hi Mr. Fornazier,

The stable branch should be used for production use.
Josef Nagy uses it for several business projects.

Regards,
Andras Pahi

**Comment by flaviofornazier** [comment]
Mr.Pahihu,

Thank you very much for your help and congratulations for your efforts.

Yes, Mr.Nagy, beautiful friend from Hungary. =)

Issue closed.

Regards.
